# BSD 3-Clause License
# Copyright (c) 2023, Alexandra Stratton, Riley Sirimongkhon-Dyck,
# Timo Aranjo, Victor Maduka, Ellia Morse, Deborah Onuosa


calculator: main.o
	g++ main.o -o calculator

clean:
	rm *.o calculator

.PHONY: clean
